### ISSUE TITLE
No converting

### ISSUE THREAD

**Issue by niccolospa** [dlion/opus2audiobot#1]
![img_2226](https://user-images.githubusercontent.com/26550959/33531609-ae5377a8-d88f-11e7-8e30-222170e5d8d4.jpg)
I did all the steps, but when it come to converting, the audio received isn't playable

**Comment by dlion** [comment]
@niccolospa Setting as `true` the debug variable what do you see as logs on the server?

**Comment by niccolospa** [comment]
![schermata 2017-12-04 alle 10 27 07](https://user-images.githubusercontent.com/26550959/33545274-e3c74632-d8dd-11e7-8dee-f1045603feb2.png)
This is what I get

**Comment by dlion** [comment]
@niccolospa Following the URI can you download and play the file .ogg?
If not the problem is online-convert.com otherwise is Telegram

**Comment by niccolospa** [comment]
Following the URI downloads an .ogg file that I can play with VLC. What I receive on telegram is an "audio" but doesn't play

**Comment by niccolospa** [comment]
I just realized that via Telegram Desktop for mac it can be played, but not through iPhone app

**Comment by niccolospa** [comment]
I just managed to do it! I changed the conversion target to mp3 instead of ogg 👍
